# Accessing/Changing Specific Elements, Rows, Columns, etc (slicing)

In [2]:
import numpy as np

In [5]:
n1 = np.array([[1,2,3,4,5,6,7,8,9],[11,12,13,14,15,16,17,18,19]])

In [6]:
n1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [8]:
# Getting specific element n1[row,col]
n1[1,3]

14

In [10]:
# Getting Specific Row
n1[1,:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
# Getting spcific column
n1[:,1]

array([ 2, 12])

In [13]:
# Getting elements more interesting [start:end:stepsize]
n1[1,1:7:2]

array([12, 14, 16])

In [15]:
# Updating Value
n1[1,4] = 3

In [17]:
n1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14,  3, 16, 17, 18, 19]])

In [19]:
# Updating value for particular range
n1[:,2] = [77,79]

In [21]:
n1

array([[ 1,  2, 77,  4,  5,  6,  7,  8,  9],
       [11, 12, 79, 14,  3, 16, 17, 18, 19]])

In [22]:
# 3-D array code

In [24]:
n2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [25]:
n2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
n2.ndim

3

In [29]:
# Getting Specific value n2[z,i,j]
n2[1,1,1]

11

In [31]:
# replacing
n2[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [33]:
n2[:,1,:] = [[1,2,3],[1,2,3]]
n2

array([[[1, 2, 3],
        [1, 2, 3]],

       [[7, 8, 9],
        [1, 2, 3]]])