# Basic Mathematics

In [1]:
import numpy as np

In [2]:
n1 = np.random.randint(7, size = (3,3))

In [3]:
n1

array([[3, 3, 5],
       [2, 4, 6],
       [2, 1, 6]])

In [5]:
n1+3

array([[6, 6, 8],
       [5, 7, 9],
       [5, 4, 9]])

In [6]:
n1-3

array([[ 0,  0,  2],
       [-1,  1,  3],
       [-1, -2,  3]])

In [7]:
n1*3

array([[ 9,  9, 15],
       [ 6, 12, 18],
       [ 6,  3, 18]])

In [8]:
n1/3

array([[1.        , 1.        , 1.66666667],
       [0.66666667, 1.33333333, 2.        ],
       [0.66666667, 0.33333333, 2.        ]])

In [9]:
n1**2

array([[ 9,  9, 25],
       [ 4, 16, 36],
       [ 4,  1, 36]], dtype=int32)

In [10]:
n2 = np.random.randint(7, size = (3,3))
n2

array([[4, 6, 5],
       [1, 6, 6],
       [4, 2, 4]])

In [11]:
n1+n2

array([[ 7,  9, 10],
       [ 3, 10, 12],
       [ 6,  3, 10]])

In [12]:
n1/n2

array([[0.75      , 0.5       , 1.        ],
       [2.        , 0.66666667, 1.        ],
       [0.5       , 0.5       , 1.5       ]])

In [13]:
n1-n2

array([[-1, -3,  0],
       [ 1, -2,  0],
       [-2, -1,  2]])