In [3]:
# be careful when copying arrays

# if this method is followed changes in the array from which data is copied is made
import numpy as np
r = np.random.randint(-10,10,size = (3,3))
r

array([[-8,  2,  8],
       [-4,  4,  5],
       [ 6,  1, -3]])

In [4]:
narray = r
narray[1,2] = 3

In [5]:
r

array([[-8,  2,  8],
       [-4,  4,  3],
       [ 6,  1, -3]])

In [6]:
narray

array([[-8,  2,  8],
       [-4,  4,  3],
       [ 6,  1, -3]])

In [7]:
f = np.full((3,3),99)
f

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [8]:
# in this changes in the copied array is made
narray = f.copy()
narray[1,2] = 3

In [9]:
f

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [10]:
narray

array([[99, 99, 99],
       [99, 99,  3],
       [99, 99, 99]])