# Initializing Different Arrays (1s, 0s, full, random, etc...)

In [2]:
import numpy as np

In [4]:
# zeros
z = np.zeros((2,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
z = z.astype('int64')

In [43]:
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [48]:
# ones
o = np.ones((3,6), dtype = 'int32')
o

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [50]:
# full
f = np.full((3,3),99)
f

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [57]:
# full_like
fl = np.full_like([3,3],10.23)
fl

array([10, 10])

In [54]:
# random
r = np.random.rand(3,3)
r

array([[0.21050905, 0.1414372 , 0.80599095],
       [0.46544489, 0.129372  , 0.04049618],
       [0.14015766, 0.72360757, 0.11291951]])

In [66]:
# rand_int
r = np.random.randint(10,size = (3,3))
r

array([[1, 9, 7],
       [4, 3, 8],
       [2, 6, 8]])

In [67]:
r = np.random.randint(-10,10,size = (3,3))
r

array([[ 8, -9, -8],
       [-6,  7,  8],
       [-9, -7,  0]])

In [70]:
# identity
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])