# Reorganizing Arrays (reshape, vstack, hstack)

In [1]:
import numpy as np

In [2]:
# Reshape
n1 = np.zeros((3,2))

In [3]:
n1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
n1.reshape(2,3)
n1

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n2 = np.array([1,2])
n2

array([1, 2])

In [12]:
# vstack
np.vstack((n1,n2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 2.]])

In [21]:
# hstack
n2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n3=np.hstack((n1,n2))
n3

array([[0., 0., 1., 2., 3.],
       [0., 0., 4., 5., 6.],
       [0., 0., 7., 8., 9.]])

In [22]:
n3.astype('int')

array([[0, 0, 1, 2, 3],
       [0, 0, 4, 5, 6],
       [0, 0, 7, 8, 9]])