In [1]:
import numpy as np

In [2]:
# 1-D
n1 = np.array([1,2,3,4,5,6,7,8,9,0])

In [3]:
# split()
np.array_split(n1,3,axis=0)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([8, 9, 0])]

In [4]:
# 2-D
n2 = np.array([[1,2,3],[4,5,6]])

In [5]:
np.array_split(n2,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [7]:
np.array_split(n2,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [38]:
# 1-D
n1 = np.array([1,2,3,4,5,6,7,8,9,0])

In [39]:
# hsplit
np.hsplit(n2,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [11]:
# vsplit
np.vsplit(n2,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]