# Statisics

In [1]:
import numpy as np

In [2]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
np.max(n1,axis=0)

array([5, 6, 7, 8])

In [4]:
np.max(n1,axis=1)

array([4, 8])

In [5]:
np.max(n1)

8

In [9]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
np.linspace(10,2,8,dtype = 'int32')

array([10,  8,  7,  6,  5,  4,  3,  2])