# The Basics

In [43]:
# pip install numpy
import numpy as np

In [44]:
n1 = np.array([1,2,3,4])

In [45]:
# 1-D array
n1

array([1, 2, 3, 4])

In [46]:
n2 = np.array([[1,2,3,4],[5,6,7,8]])

In [47]:
# 2-D array
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
# 3-D array
n3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [49]:
n3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [50]:
# Getting the dimension of the array
n1.ndim

1

In [51]:
n2.ndim

2

In [52]:
n3.ndim

3

In [53]:
# Getting the shape of the array
n1.shape

(4,)

In [54]:
n2.shape

(2, 4)

In [55]:
n3.shape

(2, 3, 3)

In [56]:
# Get type of the array
n1.dtype

dtype('int32')

In [57]:
# Total Size of the array
n1.size

4

In [58]:
n2.size

8

In [59]:
n3.size

18

In [60]:
# Item Size of the array
n1.itemsize

4

In [61]:
n2.itemsize

4

In [62]:
n3.itemsize

4

In [63]:
# Total Size in bytes
n1.nbytes

16